/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nick.smt.training.exercises;

import org.junit.jupiter.api.Test;

import nick.smt.training.exercises.intro_to_programming_exercises.Library;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
